// flow-typed signature: 3af1c442e7692b9580fdf7ad2800374c
// flow-typed version: <<STUB>>/sanitize.css_v^5.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
